# Generated by Django 2.0.5 on 2018-05-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='ano',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
