# Generated by Django 2.0.5 on 2018-05-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musica',
            name='favorita',
            field=models.BooleanField(default=False),
        ),
    ]
