# Generated by Django 2.0.5 on 2018-06-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180528_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.FileField(upload_to=''),
        ),
    ]
