# Generated by Django 2.0.5 on 2018-06-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20180601_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='arquivo_musica',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
